return {
    baseid="DST_CAVE",
    desc="洞穴设置(空洞世界)",
    worldgen_preset = "DST_CAVE",
    settings_preset = "DST_CAVE",
    override_enabled = true,
    overrides={
        -- settings
        atriumgate="veryslow",
        bats_setting="never",
        bunnymen_setting="never",
        dustmoths="never",
        earthquakes="never",
        flower_cave_regrowth="never",
        fruitfly="never",
        grassgekkos="never",
        liefs="never",
        lightflier_flower_regrowth="never",
        lightfliers="never",
        merms="never",
        molebats="never",
        moles_setting="never",
        monkey_setting="never",
        mushgnome="never",
        mushtree_moon_regrowth="never",
        mushtree_regrowth="never",
        nightmarecreatures="never",
        pigs_setting="never",
        regrowth="never",
        rocky_setting="never",
        slurtles_setting="never",
        snurtles="never",
        spider_dropper="never",
        spider_hider="never",
        spider_spitter="never",
        spider_warriors="never",
        spiderqueen="never",
        spiders_setting="never",
        toadstool="never",
        weather="never",
        wormattacks="never"
    }
}
