return {
    baseid="DST_CAVE",
    desc="洞穴生成(空洞世界)",
    worldgen_preset = "DST_CAVE",
    settings_preset = "DST_CAVE",
    override_enabled = true,
    overrides={
        -- generations
        banana="never",
        bats="never",
        berrybush="never",
        boons="never",
        branching="default",
        bunnymen="never",
        cave_ponds="never",
        cave_spiders="never",
        cavelight="default",
        chess="never",
        fern="never",
        fissure="never",
        flint="never",
        flower_cave="never",
        grass="never",
        lichen="never",
        loop="default",
        marshbush="never",
        monkey="never",
        mushroom="never",
        mushtree="never",
        prefabswaps_start="default",
        reeds="never",
        rock="never",
        rocky="never",
        sapling="never",
        slurper="never",
        slurtles="never",
        spiders="never",
        start_location="caves",
        task_set="cave_default",
        tentacles="never",
        touchstone="default",
        trees="never",
        world_size="small",
        wormlights="never",
        worms="never"
    }
}
