return {
    baseid="DST_CAVE",
    desc="洞穴生成(默认)",
    worldgen_preset = "DST_CAVE",
    settings_preset = "DST_CAVE",
    override_enabled = true,
    overrides={
        -- generations
        banana="default",
        bats="default",
        berrybush="default",
        boons="default",
        branching="default",
        bunnymen="default",
        cave_ponds="default",
        cave_spiders="default",
        cavelight="default",
        chess="default",
        fern="default",
        fissure="default",
        flint="default",
        flower_cave="default",
        grass="default",
        lichen="default",
        loop="default",
        marshbush="default",
        monkey="default",
        mushroom="default",
        mushtree="default",
        prefabswaps_start="classic",
        reeds="default",
        rock="default",
        rocky="default",
        sapling="default",
        slurper="default",
        slurtles="default",
        spiders="default",
        start_location="caves",
        task_set="cave_default",
        tentacles="default",
        touchstone="default",
        trees="default",
        world_size="default",
        wormlights="default",
        worms="default"
    }
}
