return {
    baseid="TERRARIA_CAVE",
    desc="泰拉瑞亚洞穴-世界选项",
    worldgen_preset = "DST_CAVE",
    settings_preset = "DST_CAVE",
    override_enabled = true,
    overrides={
        -- settings
        atriumgate="default",
        bats_setting="often",
        bunnymen_setting="default",
        dustmoths="default",
        earthquakes="default",
        flower_cave_regrowth="fast",
        fruitfly="default",
        grassgekkos="default",
        liefs="default",
        lightflier_flower_regrowth="default",
        lightfliers="default",
        merms="default",
        molebats="default",
        moles_setting="default",
        monkey_setting="default",
        mushgnome="default",
        mushtree_moon_regrowth="fast",
        mushtree_regrowth="fast",
        nightmarecreatures="default",
        pigs_setting="default",
        regrowth="default",
        rocky_setting="default",
        slurtles_setting="default",
        snurtles="default",
        spider_dropper="often",
        spider_hider="default",
        spider_spitter="default",
        spider_warriors="default",
        spiderqueen="default",
        spiders_setting="default",
        toadstool="default",
        weather="often",
        wormattacks="often"
    }
}