return {
    id="VOLCANO_LEVEL",
    name="Volcano",
    desc="The top of the SW volcano",
    worldgen_desc="The top of the SW volcano",
    worldgen_id="VOLCANO_LEVEL",
    worldgen_name="Volcano",
    settings_desc="The top of the SW volcano",
    settings_id="VOLCANO_LEVEL",
    settings_name="Volcano",
    required_prefabs={ "volcano_altar", "obsidian_workbench", "volcano_start" },
    required_setpieces={ "ObsidianWorkbench", "VolcanoStart", "VolcanoAltar" },
    --
    version=2,
    hideminimap=false,
    location="forest",
    max_playlist_position=999,
    min_playlist_position=0,
    numrandom_set_pieces=0,
    override_level_string=false,
    substitutes={  },
    --
    background_node_range={ 0, 0 },
    --
    overrides={
        -- settings
        alternatehunt="default",
        antliontribute="default",
        autumn="default",
        bats_setting="default",
        bearger="never",
        beefaloheat="default",
        beequeen="default",
        bees_setting="default",
        birds="never",
        brightmarecreatures="default",
        bunnymen_setting="default",
        butterfly="never",
        carrots_regrowth="default",
        catcoons="default",
        cookiecutters="default",
        crabking="default",
        crow_carnival="default",
        day="default",
        deciduousmonster="default",
        deciduoustree_regrowth="default",
        deerclops="never",
        dragonfly="default",
        dropeverythingondespawn="default",
        evergreen_regrowth="default",
        extrastartingitems="default",
        eyeofterror="default",
        fishschools="default",
        flowers_regrowth="default",
        frograin="never",
        frogs="default",
        fruitfly="default",
        gnarwail="default",
        goosemoose="default",
        grassgekkos="never",
        hallowed_nights="default",
        hound_mounds="default",
        hounds="never",
        hunt="never",
        klaus="default",
        krampus="default",
        liefs="default",
        lightning="default",
        lureplants="default",
        malbatross="default",
        merms="default",
        meteorshowers="default",
        moles_setting="default",
        moon_spider="default",
        moon_tree_regrowth="default",
        mosquitos="default",
        mutated_hounds="default",
        penguins="never",
        penguins_moon="default",
        perd="never",
        petrification="default",
        pigs_setting="default",
        rabbits_setting="default",
        regrowth="default",
        saltstack_regrowth="default",
        seasonalstartingitems="default",
        shadowcreatures="default",
        sharks="default",
        spawnprotection="default",
        specialevent="default",
        spider_warriors="default",
        spiderqueen="default",
        spiders_setting="default",
        spring="default",
        squid="default",
        summer="default",
        summerhounds="default",
        twiggytrees_regrowth="default",
        walrus_setting="default",
        wasps="default",
        weather="default",
        wildfires="never",
        winter="default",
        winterhounds="default",
        winters_feast="default",
        wobsters="default",
        year_of_the_beefalo="default",
        year_of_the_carrat="default",
        year_of_the_catcoon="default",
        year_of_the_gobbler="default",
        year_of_the_pig="default",
        year_of_the_varg="default",

        ---------- ---------- ---------- ---------- ----------
        --------------------     火山    ---------- ----------
        ---------- ---------- ---------- ---------- ----------
        -- settings - Island怪物 7 (options5)
        twister="never",
        tigershark="default",
        kraken="default",
        flup="default",
        mosquito="default",
        swordfish="default",
        stungray="default",
        -- settings - Island动物 11 (options5)
        wildbores="default",
        whalehunt="default",
        crabhole="default",
        ox="default",
        solofish="default",
        doydoy="default",           -- (defaultnever)
        jellyfish="never",
        lobster="default",
        seagull="never",
        ballphin="default",
        primeape="default",

        ---------- ---------- ---------- ---------- ----------
        -- 其他
        -- has_ocean=true,
        -- keep_disconnected_tiles=true,
        -- layout_mode="LinkNodesByKeys",
        -- no_joining_islands=true,
        -- no_wormholes_to_disconnected_tiles=true,
        -- worldseed="",
        -- wormhole_prefab="wormhole",
    }
}